module.exports = {
    generateName: () => {
        var prefix = ["absolutely", "abundant", "accessible", "acclaimed", "accommodative", "achievement", "adaptive", "admired", "animated", "approved", "assured", "attractive", "awesome", "baronial", "beaming", "beautiful", "beguiling", "beloved", "benignant", "best", "bewitching", "boss", "brainy", "breathtaking", "bubbly", "centered", "champion", "charismatic", "charming", "cheerful", "chic", "chipper", "chummy", "classy", "clever", "colorful", "comical", "communicative", "constant", "courageous", "definite", "delectable", "delicious", "delightful", "dependable", "dignified", "divine", "dreamy", "dynamite", "ecstatic", "electrifying", "employable", "empowered", "endearing", "enjoyable", "enriching", "enthusiastic", "enticing", "especial", "excellent", "exciting", "exhilarating", "exultant", "fab", "fain", "fantastic", "fashionable", "favorite", "fearless", "fetching", "fiery", "friend", "funny", "gallant", "genuine", "gifted", "gleaming", "glittering", "gnarly", "goodhearted", "grandiose", "greatest", "gumptious", "happy", "heavenly", "honorable", "hospitable", "humanitarian", "hypnotic", "ideal", "imaginative", "impeccable", "impressive", "incredible", "innovative", "insightful", "inspiring", "instinctive", "intellectual", "irresistible", "jammy", "jesting", "jolly", "jovial", "joysome", "judicious", "juicy", "just", "keen", "knightly", "knockout", "knowledgeable", "lambent", "laudable", "legendary", "likable", "lionhearted", "lively", "lovely", "luminous", "magical", "magnetic", "magnificent", "majestic", "marvelous", "masterful", "mindful", "miraculous", "motivated", "moving", "neighborly", "nifty", "noble", "numinous", "obliging", "observant", "optimistic", "orderly", "organized", "original", "outgoing", "outstanding", "overjoyed", "pally", "paramount", "passionate", "patient", "peaceful", "peachy", "peppy", "perceptive", "persevering", "persistent", "personable", "persuasive", "phenomenal", "philanthropic", "picturesque", "piquant", "playful", "polished", "posh", "prized", "proactive", "promising", "proud", "punctual", "queenly", "quirky", "rad", "radiant", "rapturous", "reassuring", "recherche", "recommendable", "refulgent", "reliable", "remarkable", "resilient", "resourceful", "respectable", "revolutionary", "saccharine", "sagacious", "savvy", "sensational", "sincere", "snappy", "snazzy", "spellbinding", "splendiferous", "spunky", "stellar", "striking", "teeming", "thoughtful", "thriving", "timeless", "tolerant", "trailblazing", "transcendental", "tubular", "upbeat", "uplifting", "upstanding", "urbane", "valiant", "vibrant", "victorious", "visionary", "vivacious", "warm", "whimsical", "wholehearted", "winsome", "wise", "witty", "wizardly", "wondrous", "worldly", "xenial", "xenodochial", "yummiest", "zappy", "zazzy", "zealful", "zealous"];

        var suffix = ["adult", "age", "amount", "area", "back", "bed", "blood", "body", "book", "box", "bulb", "bunch", "business", "camera", "chicken", "chocolates", "city", "clothes", "colors", "company", "computer", "continent", "council", "country", "course", "cycle", "dates", "day", "desk", "door", "fact", "factory", "farm", "farmer", "fish", "floor", "flowers", "food", "fridge", "future", "game", "garden", "glass", "group", "health", "hill", "idea", "image", "industry", "island", "jewelry", "job", "land", "law", "leaves", "leg", "letter", "life", "magazine", "market", "metal", "mirror", "mobile", "money", "morning", "mountain", "movie", "name", "nest", "news", "ocean", "painter", "park", "party", "pen", "pencil", "person", "picture", "pillow", "place", "plant", "pond", "rain", "rate", "result", "ring", "road", "rock", "room", "rope", "shapes", "ship", "shop", "site", "skin", "snacks", "song", "sort", "sound", "soup", "sports", "state", "stone", "street", "system", "taxi", "tea", "team", "tractor", "trade", "train", "video", "view", "water", "waterfall", "week", "wood", "word", "year", "yesterday"];

        var name = prefix[getRandomInt(0, prefix.length + 1)] + '-' + suffix[getRandomInt(0, suffix.length + 1)];
        return name;
    }
}


function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min)) + min;
}